// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetServers():Promise<Array<string>>;

export function GetStatus():Promise<string>;

export function IsAuthorized():Promise<boolean>;

export function LinkPlex():Promise<void>;

export function Listener():Promise<void>;

export function SetServer(arg1:string):Promise<void>;
