// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetServers() {
  return window['go']['main']['App']['GetServers']();
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function IsAuthorized() {
  return window['go']['main']['App']['IsAuthorized']();
}

export function LinkPlex() {
  return window['go']['main']['App']['LinkPlex']();
}

export function Listener() {
  return window['go']['main']['App']['Listener']();
}

export function SetServer(arg1) {
  return window['go']['main']['App']['SetServer'](arg1);
}
